In [2]:
import numpy as np

### One dimensional array

In [6]:
ar = np.array([1,2,3,4,5])
print(ar)
ar

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [8]:
ar = np.array((1,2,3,4,5)) # '()' can also be used
print(ar)
ar

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [14]:
# indexing in array

print(ar[0])
print(ar[-1])
print(ar[1:4])
print(ar[::-1])

1
5
[2 3 4]
[5 4 3 2 1]


In [15]:
ar

array([1, 2, 3, 4, 5])

In [18]:
ar.ndim  # dimension

1

In [20]:
ar.size  # gives total elements

5

#### 2 - Dimensional Array

In [24]:
a=np.array([[1,4],[2,9],[3,6],[3,5]])
print(a)
a

[[1 4]
 [2 9]
 [3 6]
 [3 5]]


array([[1, 4],
       [2, 9],
       [3, 6],
       [3, 5]])

In [28]:
# indexing

print(a[0])
print(a[1])
print(a[2][1])

[1 4]
[2 9]
6


In [29]:
# dimension

a.ndim

2

In [30]:
# data type

a.dtype

dtype('int64')

In [33]:
# cretaes an array filled with zeroes

zeros_array_1 = np.zeros(5)
print(zeros_array_1)

[0. 0. 0. 0. 0.]


In [34]:
zeros_array_2 = np.zeros((2,3))
print(zeros_array_2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# creates an array filled with ones

ones_array_1 = np.ones(4)
print(ones_array_1)

[1. 1. 1. 1.]


In [36]:
ones_array_2 = np.ones((4,2))
print(ones_array_2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
# creates an array filled with a specific value

full_array_1 = np.full(3,7)
print(full_array_1)

[7 7 7]


In [45]:
full_array_2 = np.full((3,5),7)
print(full_array_2)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [46]:
# shape

a=np.array([[1,4],[2,9],[3,6],[3,5]])
a.shape

(4, 2)

In [86]:
# reshape

c = a.reshape(2,4)
print(c)
print(c.shape)

[[1 4 2 9]
 [3 6 3 5]]
(2, 4)


In [55]:
# converts multidimensional array into a single dimensional array

a=np.array([[1,4],[2,9],[3,6],[3,5]])
d = a.ravel()
print(d)

[1 4 2 9 3 6 3 5]


In [56]:
# Minimum and Maximum of an array

a=np.array([[1,4],[2,9],[3,6],[3,5]])

print(a.min())
print(a.max())

1
9


#### 3 Dimensional array

In [81]:
b=np.array([[[1,4,8],[2,9,9]],[[3,6,9],[3,5,4]]],dtype=np.float64)  # also dtype = int/float/complex/str
b

array([[[1., 4., 8.],
        [2., 9., 9.]],

       [[3., 6., 9.],
        [3., 5., 4.]]])

In [68]:
print(b[0][1][0])

2.0


In [69]:
b.ndim

3

In [70]:
b.dtype

dtype('float64')

In [71]:
b.shape

(2, 2, 3)

In [74]:
b.size

12

#### Creating a random array

In [85]:
# np.array(start,stop,step) - creates an array with evenly spaced values within a range

arr = np.arange(0,10,2) 
print(arr)

[0 2 4 6 8]


In [89]:
arr = np.arange(0,1,0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8]


In [90]:
arr = np.arange(0,1,0.2,dtype=complex)
print(arr)

[0. +0.j 0.2+0.j 0.4+0.j 0.6+0.j 0.8+0.j]


##### np.linspace

In [95]:
# creates an array of evenly spaced values between two numbers including the stop values

arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [96]:
arr,step = np.linspace(0,10,5,retstep=True)
print(arr)
print(step)

[ 0.   2.5  5.   7.5 10. ]
2.5


#### 1. Random arrays using Numpy's random module

In [109]:
# generate random floats in the range [0.0,1.0] from a uniform distribution

arr = np.random.rand(3)
print(arr)

[0.93651533 0.29816125 0.39316806]


In [108]:
arr2d = np.random.rand(2,3)
print(arr2d)

[[0.60950963 0.15889753 0.74151936]
 [0.81645573 0.93888127 0.26857643]]


In [111]:
# generate random floats from a standard normal distribution (mean = 0, std = 1)

arr = np.random.randn(4)
print(arr)

[-1.39717096 -1.62928454  0.79892324 -0.6126267 ]


In [112]:
arr2d = np.random.randn(2,3)
print(arr2d)

[[ 0.13701527  0.63324808  1.53980508]
 [ 1.06945077 -0.48703554 -1.61207114]]


In [114]:
# generates random integers from a given range

arr = np.random.randint(1,10,size=5)
print(arr)

[3 6 7 7 7]


In [115]:
arr2d = np.random.randint(1,10,size=(2,4))
print(arr2d)

[[3 7 8 2]
 [2 9 1 5]]


##### numpy.eye() function

In [116]:
""" This is a function in the numpy library that cretaes a 2D array with ones on the diagonal and zeroes elesewhere"""

' This is a function in the numpy library that cretaes a 2D array with ones on the diagonal and zeroes elesewhere'

In [119]:
# cretaes a 2*2 identity matrix

identity_matrix = np.eye(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


In [118]:
# cretaes a 3*3 identity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [122]:
# if you want the array to contain integers, you can specify the dtype

identity_matrix = np.eye(3,dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [124]:
# creation of rectangular matrix

rectangular_matrix = np.eye(3,5)  # creates a 3*5 rectangular matrix 
print(rectangular_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [127]:
# specifying a diagonal offset - it refers to shifting the location of the diagonal filled with ones within the matrix

# creating a 4*4 matrix with diagonal offset

matrix = np.eye(4,k=1)
print(matrix)
print("##########")
print("##########")
matrix2 = np.eye(4,k=2)
print(matrix2)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
##########
##########
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Empty and full Numpy array

In [132]:
"""np.empty() - cretaes an array without initializing its values. The contents will be whatever happens to already exist at that memory location - essentially garbage values (uninitialized)"""

'np.empty() - cretaes an array without initializing its values. The contents will be whatever happens to already exist at that memory location - essentially garbage values (uninitialized)'

In [148]:
arr=np.empty((2,3))
print(arr)

[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]


In [133]:
""" np.full(shape,fill_value) - creates an array of a given shape, filled with a specified value """

' np.full(shape,fill_value) - creates an array of a given shape, filled with a specified value '

In [150]:
arr=np.full((2,3),7,dtype=float)
print(arr)

[[7. 7. 7.]
 [7. 7. 7.]]


## Slicing

#### 1D slicing

In [139]:
arr = np.array([10,20,30,40,50])
print(arr)
print("#########")
print(arr[1:4])
print(arr[:3])
print(arr[::2])
print(arr[-2:])

[10 20 30 40 50]
#########
[20 30 40]
[10 20 30]
[10 30 50]
[40 50]


#### 2D Slicing

In [144]:
# A 2D array is like a matrix

#Syntax: array[row_start:row_end, col_start:col_end]

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print("#########")
print(arr2d[0:2,1:3])
print("#########")
print(arr2d[:,0])
print("#########")
print(arr2d[1,:])
print("#########")
print(arr2d[::2,::2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
#########
[[2 3]
 [5 6]]
#########
[1 4 7]
#########
[4 5 6]
#########
[[1 3]
 [7 9]]


#### nD Slicing (3D and beyond)

In [153]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3d)
print("#########")
print(arr3d[0,0,1])
print(arr3d[1,1,0])
print("#########")
print(arr3d[0])
print("#########")
print(arr3d[1,0])
print("#########")
print(arr3d[1,1,0])
print("#########")
print(arr3d[:,0,0])
print("#########")
print(arr3d[:,:,1])
print("#########")
print(arr3d[:,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
#########
2
7
#########
[[1 2]
 [3 4]]
#########
[5 6]
#########
7
#########
[1 5]
#########
[[2 4]
 [6 8]]
#########
[[3 4]
 [7 8]]


#### Matrix Inversion

In [157]:
A = np.array([[4,7],[2,6]])
print(A)

print("#########")
# compute the inverse

A_inv = np.linalg.inv(A)
print(A_inv)

[[4 7]
 [2 6]]
#########
[[ 0.6 -0.7]
 [-0.2  0.4]]


#### Some algebraic functions in arrays



In [161]:
# Sum

arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr)) # gives sum of all elemnts in an array
print(np.sum(arr,axis=0)) # gives column sums
print(np.sum(arr,axis=1)) # gives row sums

21
[5 7 9]
[ 6 15]


In [162]:
# Mean

arr=np.array([[1,2,3],[4,5,6]])
print(np.mean(arr)) # gives mean of all elements in an array
print(np.mean(arr,axis=0)) # gives column means
print(np.mean(arr,axis=1)) # gives row means

3.5
[2.5 3.5 4.5]
[2. 5.]


In [163]:
# Max

arr=np.array([[1,2,3],[4,5,6]])
print(np.max(arr)) # gives maximum of all elements in an array
print(np.max(arr,axis=0)) # gives column maximums
print(np.max(arr,axis=1)) # gives row maximums

6
[4 5 6]
[3 6]


In [164]:
# Min

arr=np.array([[1,2,3],[4,5,6]])
print(np.min(arr)) # gives minimum of all elements in an array
print(np.min(arr,axis=0)) # gives column minimums
print(np.min(arr,axis=1)) # gives row minimums

1
[1 2 3]
[1 4]


#### Dot product of arrays and matrices

In [165]:
# dot product of two arrays

a=np.array([1,2,3])
b=np.array([4,5,6])
dot = np.dot(a,b) # (1*4 + 2*5 + 3*6)
print(dot)

32


In [166]:
# dot product of two matrices

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
res = np.dot(A,B)  # normal matrix multiplication
print(res)

[[19 22]
 [43 50]]


In [167]:
res = np.matmul(A,B)
print(res)

[[19 22]
 [43 50]]


#### Basic Arithmetic functions in arrays and matrices

In [192]:
# operations in arrays

print(np.add([1,2],[3,4]))  # addition
print(np.subtract([1,2],[3,4]))  # subtraction
print(np.multiply([1,2],[3,4]))  # multiplication
print(np.divide([4,6],[2,3]))  # division
print(np.power([3,2],3))  # raise to power 3
print(np.mod([10,12],3))  # gives reminder

[4 6]
[-2 -2]
[3 8]
[2. 2.]
[27  8]
[1 0]


In [195]:
# operations in matrices

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[9,8]])
print("A:",A)
print("B:",B)
print("###########")
print(np.add(A,B))  # addition
print("###########")
print(np.subtract(A,B))  # subtraction
print("###########")
print(np.multiply(A,B))  # multiplication
print("###########")
print(np.divide(B,A))  # division
print("###########")
print(np.power(A,2))  # raise to power 3
print("###########")
print(np.mod(B,3))  # gives reminder

A: [[1 2]
 [3 4]]
B: [[5 6]
 [9 8]]
###########
[[ 6  8]
 [12 12]]
###########
[[-4 -4]
 [-6 -4]]
###########
[[ 5 12]
 [27 32]]
###########
[[5. 3.]
 [3. 2.]]
###########
[[ 1  4]
 [ 9 16]]
###########
[[2 0]
 [0 2]]


#### Square Matrix

In [176]:
M = np.array([[1,2],[3,4]])
res = np.matmul(M,M)
print(res)

[[ 7 10]
 [15 22]]


#### Cumulative operations in Numpy

In [177]:
""" It refers to the operations that accumulate results across an array in a simple fashion"""

' It refers to the operations that accumulate results across an array in a simple fashion'

In [178]:
# Cumulative sum - computes the cumulative sum of array elements

a=np.array([1,2,3,4])
np.cumsum(a)

array([ 1,  3,  6, 10])

In [179]:
# cumulative product - computes the cumulative product of array elements 

a=np.array([1,2,3,4])
np.cumprod(a)

array([ 1,  2,  6, 24])

In [180]:
# cumulative maximum

a=np.array([2,1,5,3])
np.maximum.accumulate(a)

array([2, 2, 5, 5])

In [187]:
# cumulative minimum

b=np.array([4,2,7,1])
np.minimum.accumulate(b)

array([4, 2, 2, 1])

In [188]:
# Axis Support

"""All cumulative operations support the axis parameters for multi-dimensional array"""

B=np.array([[1,2,3],[4,5,6]])
print(B)
print("###########")
print(np.cumsum(B,axis=0))  # axis=0 means column wise
print(np.cumsum(B,axis=1))  # axis=1 means row wise
print("###########")
print(np.cumprod(B,axis=0))
print(np.cumprod(B,axis=1))
print("###########")
print(np.minimum.accumulate(B,axis=0))
print(np.minimum.accumulate(B,axis=1))
print("###########")
print(np.maximum.accumulate(B,axis=0))
print(np.maximum.accumulate(B,axis=1))

[[1 2 3]
 [4 5 6]]
###########
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
###########
[[ 1  2  3]
 [ 4 10 18]]
[[  1   2   6]
 [  4  20 120]]
###########
[[1 2 3]
 [1 2 3]]
[[1 1 1]
 [4 4 4]]
###########
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


#### Matrix inversion and determinant

In [3]:
# compute the inverse of a square matrix

A=np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
I = np.dot(A,A_inv)
print(I)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [9]:
# compute the determinant of a square matrix

A=np.array([[1,2],[3,4]])
A_det = np.linalg.det(A)
print(A_det)

-2.0000000000000004


#### Eigen values & Eigen vectors

In [10]:
# compute eigen values and eigen vectors of a square matrix

eigvals,eigvecs = np.linalg.eig(A)
print("Eigenvalues:\n",eigvals)
print("Eigenvectors:\n",eigvecs)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [11]:
# Note1: eigenvalues of a squeare matrix A is the value E that satisfies det(A-EI)=0, where I is the identity matrix
# Note2: eigenvectors of a square matrix A, is the valiue of vector V satisfying (A-EI)V=0, where E is the eigenvalues

### Median of array and matrix

In [12]:
# median of an array with odd number of elements

arr = np.array([1,3,5,7,9])
print(np.median(arr))

5.0


In [13]:
# median of an array with even number of elements

arr = np.array([1,3,5,7,9,10])
print(np.median(arr))

6.0


In [14]:
# median of a matrix - column wise

matrix = np.array([[10,20,30],[40,50,60]])
print(np.median(matrix,axis=0))

[25. 35. 45.]


In [15]:
# median of a matrix - column wise

matrix = np.array([[10,20,30],[40,50,60]])
print(np.median(matrix,axis=1))

[20. 50.]


## Inner product of vectors and matrices

Inner product or dot product is the sum you get by multiplying matching 