In [1]:
c=4
a=5
def f():
    b=6
    print(b)
    print(a)
    c=7
    print(c)

In [7]:
#f()
print(a)
print(c)
print(b)

5
4


NameError: name 'b' is not defined

In [9]:
def f():
    e=5
    return e

In [10]:
f()

5

In [11]:
print(e)

NameError: name 'e' is not defined

In [14]:
def h():
    print("A")
    a=3
    b=5
    c=a+b
    print("Something")
    return
    print("B")
    print("C")
    d=5

In [15]:
h()

A
Something


In [24]:
def h():
    print("A")
    a=3
    b=5
    c=a+b
    print("Something")
    return c

In [25]:
h()

A
Something


8

In [26]:
def r():
    print("A")
    a=3
    b=5
    c=a+b
    print("Something")
    return

In [27]:
print(type(r()))

A
Something
<class 'NoneType'>


In [34]:
def w():
    a=5
    b=7
    d="Something"
    print("A")
    return d

In [35]:
print(type(w()))

A
<class 'str'>


In [49]:
def add(*argst):
    sum=0
    for i in range(0,len(argst)):
        sum=sum+argst[i]
    print("Sum: ",sum)
    return sum

In [51]:
add(1,45,21,4)

Sum:  71


71

In [52]:
a="Hello"

In [53]:
a[0]

'H'

In [58]:
b=a.replace("H","G")
print(b)

&&Gello&&


In [55]:
print(a)

Hello


In [56]:
a[0]="G"

TypeError: 'str' object does not support item assignment

In [67]:
a="!%&&Hell%&"
a.strip("&%")

'!%&&Hell'

In [68]:
a="abc;def;9;ghi"
L=a.split(";")
print(L)

['abc', 'def', '9', 'ghi']


In [70]:
print(L[2])
type(L[3])

9


str

In [78]:
a="abc;def;9&ghi"
L=a.split(";")
print(L)

['abc', 'def', '9&ghi']


In [72]:
print(a)

abc;def;9&ghi


In [80]:
L={1,2,3}

In [82]:
a="uiLPo"
print(a.capitalize())

Uilpo


In [91]:
print('We are learning \'Strings\'now')

We are learning 'Strings'now


In [94]:
a="sdp\"dgfg"
print(a)

sdp"dgfg


In [108]:
print("""My name is Vishnu
       I am 28""")

My name is Vishnu
       I am 28


Numby

In [1]:
import numpy as np

In [6]:
n1=np.array([1,2,3,4])
n2=np.array((5.1,6.3,7,8.2))
print(n1)
type(n1)
print(n2)
type(n2)
n1.dtype

[1 2 3 4]
[5.1 6.3 7.  8.2]


dtype('int64')

In [7]:
n2.dtype

dtype('float64')

In [8]:
type(n1)

numpy.ndarray

In [9]:
type(n2)

numpy.ndarray

In [12]:
n3=np.array([1,"a",3,4])
print(n3)

['1' 'a' '3' '4']


In [13]:
type(n3)

numpy.ndarray

In [14]:
n3.dtype

dtype('<U21')

In [15]:
n4=np.array(["a","b","c"])

In [16]:
print(n4)
type(n4)

['a' 'b' 'c']


numpy.ndarray

In [17]:
n4.dtype

dtype('<U1')

In [18]:
n4.ndim

1

In [42]:
n5=np.array([[1,2,3],[4,5.7,6]],dtype="complex")
print(n5)
type(n5)
n5.dtype
n5.ndim

[[1. +0.j 2. +0.j 3. +0.j]
 [4. +0.j 5.7+0.j 6. +0.j]]


2

In [43]:
type(n5)

numpy.ndarray

In [44]:
n5.dtype

dtype('complex128')

In [47]:
n6=np.array(["a","b","c"],dtype="i")
print(n6)

ValueError: invalid literal for int() with base 10: 'a'

In [48]:
n6.dtype

dtype('<U1')

In [50]:
n7=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(n7)
n7.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [55]:
print(n7[1,1,0])

7


In [62]:
n8=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[-1,-2],[-3,-4]],[[-5,-6],[-7,-8]]]],dtype="complex")
n8.ndim

4

In [63]:
print(n8)

[[[[ 1.+0.j  2.+0.j]
   [ 3.+0.j  4.+0.j]]

  [[ 5.+0.j  6.+0.j]
   [ 7.+0.j  8.+0.j]]]


 [[[-1.+0.j -2.+0.j]
   [-3.+0.j -4.+0.j]]

  [[-5.+0.j -6.+0.j]
   [-7.+0.j -8.+0.j]]]]


In [61]:
print(n8[1,0,0,0])

1


In [64]:
n=np.array([[1,2],[3,4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [65]:
n8.shape

(2, 2, 2, 2)

In [66]:
n=np.array([1])
n.ndim

1

In [68]:
n7=np.array([[[1,2,-1],[3,4,-2]],[[5,6,-3],[7,8,-4]]])
n7.shape

(2, 2, 3)

In [72]:
#n7.shape[0] # no of 2 dimensional arrays
#n7.shape[1] # no of 1 dimensional areas in each 2 dimensional arrays
n7.shape[2] # no of elements in each 1 dimensioanl arrays

3

In [79]:
n=np.array(3)
n.ndim

0

In [77]:
print(n)

3


In [82]:
n7=np.array([[[1,2,-1],[3,4,-2]],[[5,6,-3],[7,8,-4]]])
n7.size # gives total no of elements

12

In [84]:
n7.nbytes

96

In [91]:
#to create an array of continous numbers

a=np.arange(100)  # creates an array from 0 to that given number minus one
print(a)
b=np.arange(20,100) # creates an array from starting number to that given number minus one
print(b)
c=np.arange(20,100,2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [93]:
a=list(range(0,100))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [96]:
a=np.random.permutation(10) # gives a random shuffled list
print(a)

b=np.random.permutation(np.arange(10))
print(b)

[8 1 2 6 4 3 9 0 5 7]
[4 1 8 5 2 7 9 6 0 3]


In [103]:
integer=np.random.randint(20,30) # gives a random integer between 20 & 30
print(integer)

26


In [106]:
a=np.arange(10)
m1=a.reshape(2,5) # makes 2 dimensional arrays containing 5 elements each or a matrix with 2 rows and 5 coloumns
print(m1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [107]:
m.shape

(2, 5)

In [111]:
a=np.arange(10)
m2=a.reshape(5,2) # makes 2 dimensional arrays containing 2 elements each or a matrix with 5 rows and 2 coloumns
print(m2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [110]:
m2.shape

(5, 2)

In [116]:
A=np.random.rand(10) # creates a array of 10 random numbers between 0 and 1
print(A)

[0.50628862 0.76817544 0.30880492 0.87133808 0.37902732 0.67444902
 0.13108367 0.30162234 0.03750012 0.46075957]


In [118]:
B=np.random.rand(3,5)
print(B)

[[0.92074351 0.28678095 0.08376214 0.85009206 0.01188085]
 [0.52807164 0.16276232 0.19185002 0.4961852  0.87596246]
 [0.52411862 0.8158992  0.35142771 0.37296399 0.90737519]]


In [119]:
B.shape

(3, 5)

Slicing in numpy

In [121]:
a=np.array([1,2,3,4,5,6])
print(a)
b=a[:4]
print(b)

[1 2 3 4 5 6]
[1 2 3 4]


In [126]:
b[0]=100 # change in b and a reflects each other
print(b)
print(a)

[100  50   3   4]
[100  50   3   4   5   6]


In [125]:
a[1]=50
print(a)
print(b)

[100  50   3   4   5   6]
[100  50   3   4]


In [127]:
a=np.array([1,2,3,4,5,6])
print(a)
b=a[:4].copy()
print(b)

[1 2 3 4 5 6]
[1 2 3 4]


In [128]:
b[0]=100
print(b)
print(a)

[100   2   3   4]
[1 2 3 4 5 6]


In [133]:
# to find the index of a particular element in an array

A=np.array([1,2,8,9,25,4,9,10])
idx=np.argwhere(A==25)[0][0]
print(idx)

4


In [140]:
# to access elements in a matrix

B=np.round(10*np.random.rand(5,4))
B

array([[4., 6., 8., 2.],
       [6., 2., 8., 8.],
       [9., 8., 4., 4.],
       [5., 5., 8., 5.],
       [1., 8., 8., 5.]])

In [143]:
print(B[2,1]) # acees the element in row 3 and coloumn 2

8.0


In [149]:
print(B[1,:]) # returns 2nd row

[6. 2. 8. 8.]


In [150]:
print(B[:,2]) # returns 3rd coloumn

[8. 8. 4. 8. 8.]


In [151]:
print(B[1:3,2:4]) # returns a submatri

[[8. 8.]
 [4. 4.]]
